### ISSUE TITLE
StatHooks: failed to apply IL patch (regen modifiers)

### ISSUE THREAD

**Issue by TheUndeadCpt** [ThinkInvis/RoR2-TILER2#15]
With Aetherium installed Tiler2 throws the above error. Now I'm not exactly sure how this effects the mods that throw the error when they try to hook RecalculateStats (theres a few) however given 3.0.4 attempts to prevent this I figured to report about it.

[LogOutput.log](https://github.com/ThinkInvis/RoR2-TILER2/files/6033820/LogOutput.log)

**Comment by TheUndeadCpt** [comment]
Well, one thing I have noticed is massive hp regen when you have shields, disabled aetherium and it was normal.

**Comment by ThinkInvis** [comment]
Basically, this means that both TILER2 and another mod (probably Aetherium in this case) tried to change the same bit of vanilla code, and that that other mod got to it first and changed it sufficiently that TILER2 can no longer recognize what it's supposed to modify.

Because of how much of a vitally important mess RecalculateStats is, it's one of the most likely places for this to happen. I'll try to see about making my IL patch more resilient, but it might be that Aetherium's author has to change theirs instead.

**Comment by cheeeeeeeeeen** [comment]
This is one of the reasons why I didn't want to separate from TILER2. It's too precious for me to leave behind.

**Comment by ThinkInvis** [comment]
Closing as irrelevant: StatHooks is no longer a TILER2 module, and has been migrated to R2API.RecalculateStatsAPI. Coincidentally, this should make it more compatible with other mods -- or at least less likely to be the one to break.
