### ISSUE TITLE
Cannot Start a Run with TILER2 & Dependents installed

### ISSUE THREAD

**Issue by Xaenogen** [ThinkInvis/RoR2-TILER2#29]
### Describe the Bug

Whenever I load up ROR2 with TILER2, TinkersSatchel, and ClassicItems installed, I am unable to start a run from the character selection screen. The button is highlighted and plays the sound when clicked, but the game just freezes for a moment and then does not begin a run. This bug does not occur when I do not have these mods installed.

### To Reproduce
1. Install the aforementioned mods through r2modman
2. Launch Modded game
3. Once game is loaded, go to single player character selection menu.
4. Attempt to start a run with any survivor

### Console Log

[LogOutput.log](https://github.com/ThinkInvis/RoR2-TILER2/files/8984137/LogOutput.log)

**Comment by ThinkInvis** [comment]
This is an incompatibility with another mod. Which one isn't clear from any log messages, and there are far too many active to easily diagnose otherwise. All I can recommend is that you attempt to pare down your mod list, especially anything last updated more than a few months ago (due to base game patches).
